#!/usr/bin/env bash
set -euo pipefail

# Bash customizations live in ~/.bashrc.d/ so they can be regenerated on every
# create without appending duplicates to ~/.bashrc. Edit this script (not the
# generated file) to change them; the generated file is overwritten each run.
mkdir -p "$HOME/.bashrc.d"

git config --global color.ui auto

# Fedora's skel ~/.bashrc already sources ~/.bashrc.d/*, but the home volume
# may carry an older/custom ~/.bashrc, so make sure the hook exists.
grep -qF '.bashrc.d' "$HOME/.bashrc" 2>/dev/null || cat >> "$HOME/.bashrc" <<'EOF'

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        [ -f "$rc" ] && . "$rc"
    done
fi
unset rc
EOF

cat > "$HOME/.bashrc.d/10-devcontainer.sh" <<'EOF'
# Generated by .devcontainer/scripts/post-create/20-customize-bash.sh

# Only for interactive shells.
[[ $- == *i* ]] || return 0

# Colors for ls/grep/git/less.
export CLICOLOR=1
alias ls='ls --color=auto'
alias ll='ls -alF --color=auto'
alias grep='grep --color=auto'
export LESS='-R'

# History: bigger, deduplicated, shared across terminals.
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth:erasedups
shopt -s histappend
PROMPT_COMMAND="history -a${PROMPT_COMMAND:+; $PROMPT_COMMAND}"

# Colored prompt: user@host:cwd (git-branch)$
if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
    . /usr/share/git-core/contrib/completion/git-prompt.sh
    GIT_PS1_SHOWDIRTYSTATE=1
    PS1='\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0;33m\]$(__git_ps1 " (%s)")\[\e[0m\]\$ '
else
    PS1='\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\$ '
fi
EOF
